"use client";

import { useState, useEffect, useRef } from "react";
import {
  XCircleIcon,
  CopyIcon,
  ShareIcon,
  BoxArrowDownIcon,
} from "@phosphor-icons/react";
import { formatAmount } from "../../lib/utils";
import QRCodeStyling from "qr-code-styling";

interface QRCodePopupProps {
  isOpen: boolean;
  onClose: () => void;
  amount: string;
  selectedToken: string;
  username: string;
}

export default function QRCodePopup({
  isOpen,
  onClose,
  amount,
  selectedToken,
  username,
}: QRCodePopupProps) {
  const [copied, setCopied] = useState(false);
  const qrRef = useRef<HTMLDivElement>(null);
  const qrCode = useRef<QRCodeStyling | null>(null);

  // Sample token options
  const tokenOptions = [
    { symbol: "USDC", name: "USD Coin", icon: "💵" },
    { symbol: "ETH", name: "Ethereum", icon: "⟠" },
    { symbol: "BTC", name: "Bitcoin", icon: "₿" },
  ];

  const selectedTokenInfo = tokenOptions.find(
    (t) => t.symbol === selectedToken
  );

  // Generate a sample payment link (in a real app, this would be generated by your backend)
  const paymentLink = `app.getpaid.co/r/${Math.random()
    .toString(36)
    .substring(2, 8)
    .toUpperCase()}`;

  const handleCopyLink = async () => {
    try {
      await navigator.clipboard.writeText(paymentLink);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error("Failed to copy link:", err);
    }
  };

  const handleShareLink = async () => {
    if (navigator.share) {
      try {
        await navigator.share({
          title: `Payment Request from ${username}`,
          text: `${username} is requesting $${formatAmount(
            amount
          )} ${selectedToken}`,
          url: paymentLink,
        });
      } catch (err) {
        console.error("Failed to share:", err);
      }
    } else {
      // Fallback to copying if sharing is not supported
      handleCopyLink();
    }
  };

  // Generate QR Code
  useEffect(() => {
    if (isOpen && qrRef.current && !qrCode.current) {
      qrCode.current = new QRCodeStyling({
        width: 224, // 56 * 4 = 224px
        height: 224,
        type: "svg",
        data: paymentLink,
        dotsOptions: {
          color: "#000000",
          type: "dots",
        },
        backgroundOptions: {
          color: "#FFFFFF",
        },
        imageOptions: {
          crossOrigin: "anonymous",
          margin: 8,
          hideBackgroundDots: true,
          imageSize: 0.4,
        },
        cornersSquareOptions: {
          type: "extra-rounded",
          color: "#000000",
        },
        cornersDotOptions: {
          type: "dot",
          color: "#000000",
        },
      });

      qrCode.current.append(qrRef.current);
    }

    return () => {
      const currentQrRef = qrRef.current;
      if (currentQrRef && qrCode.current) {
        currentQrRef.innerHTML = "";
        qrCode.current = null;
      }
    };
  }, [isOpen, paymentLink]);

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-end justify-center">
      {/* Overlay */}
      <div
        className="absolute inset-0 bg-black/60 backdrop-blur-sm transition-opacity duration-300"
        onClick={onClose}
      />

      {/* Modal */}
      <div
        className="relative w-full bg-white rounded-t-3xl shadow-xl transition-transform duration-300"
        style={{
          animation: "slideUp 0.3s cubic-bezier(0.4,0,0.2,1)",
        }}
      >
        {/* Header */}
        <div className="flex items-center justify-between p-4 pb-2">
          <div className="flex items-center">
            <div className="w-8 h-8 bg-green-500 rounded-full flex items-center justify-center mr-3">
              <BoxArrowDownIcon
                size={20}
                weight="fill"
                className="text-white"
              />
            </div>
            <span className="text-xl font-semibold text-black">Request</span>
          </div>
          <button
            onClick={onClose}
            className="w-8 h-8 bg-gray-200 rounded-full flex items-center justify-center hover:bg-gray-300 transition-colors"
          >
            <svg
              className="w-4 h-4 text-gray-600"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M6 18L18 6M6 6l12 12"
              />
            </svg>
          </button>
        </div>

        {/* Content */}
        <div className="px-4 pb-4 space-y-4">
          {/* Username Display */}
          <div className="text-center">
            <div className="text-xs text-gray-500 mb-1">Requesting from</div>
            <div className="text-sm font-semibold text-black">{username}</div>
          </div>

          {/* QR Code */}
          <div className="flex justify-center">
            <div className="w-56 h-56 bg-white rounded-lg flex items-center justify-center relative">
              <div
                ref={qrRef}
                className="w-full h-full flex items-center justify-center"
              />
              {/* Center Logo/Image */}
              <div className="absolute inset-0 flex items-center justify-center pointer-events-none">
                <div className="w-16 h-16 bg-black rounded-full flex items-center justify-center">
                  <div className="w-12 h-12 bg-white rounded-full flex items-center justify-center">
                    <span className="text-sm font-bold">👤</span>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Amount and Token */}
          <div className="flex items-center justify-center gap-3">
            <div className="text-4xl font-bold text-black">
              ${formatAmount(amount)}
            </div>
            <div className="inline-flex items-center bg-gray-100 rounded-full px-3 py-1">
              <div className="w-4 h-4 bg-blue-500 rounded-full flex items-center justify-center mr-2">
                <span className="text-white text-xs font-bold">$</span>
              </div>
              <span className="text-sm font-medium text-gray-700">
                {selectedToken}
              </span>
            </div>
          </div>

          {/* Payment Link */}
          <div className="space-y-2">
            <div className="flex items-center justify-between bg-gray-100 rounded-xl p-3">
              <span className="text-sm text-gray-600 truncate flex-1 mr-2">
                {paymentLink}
              </span>
              <button
                onClick={handleCopyLink}
                className="flex-shrink-0 w-8 h-8 bg-blue-500 rounded-lg flex items-center justify-center hover:bg-blue-600 transition-colors"
              >
                <CopyIcon size={16} weight="fill" className="text-white" />
              </button>
            </div>
            {copied && (
              <div className="text-center text-sm text-green-600">
                Link copied to clipboard!
              </div>
            )}
          </div>

          {/* Share Button */}
          <button
            onClick={handleShareLink}
            className="w-full bg-black text-white py-4 rounded-xl font-semibold text-lg hover:bg-gray-800 transition-colors flex items-center justify-center"
          >
            <ShareIcon size={20} weight="fill" className="mr-2" />
            Share link
          </button>
        </div>
      </div>

      <style jsx global>{`
        @keyframes slideUp {
          from {
            transform: translateY(100%);
            opacity: 0;
          }
          to {
            transform: translateY(0);
            opacity: 1;
          }
        }
      `}</style>
    </div>
  );
}
